# Generated by Django 5.2.10 on 2026-02-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrios',
            old_name='localidad',
            new_name='BaLocalidad',
        ),
        migrations.RenameField(
            model_name='barrios',
            old_name='municipio',
            new_name='BaMunicipio',
        ),
        migrations.RenameField(
            model_name='barrios',
            old_name='nombre_barrio',
            new_name='BaNombreBarrio',
        ),
        migrations.AlterField(
            model_name='users',
            name='UsPass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PASSWORD'),
        ),
        migrations.AlterModelTable(
            name='barrios',
            table='Barrios',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='Localidad',
        ),
    ]
